spring:
  application:
    name: eazy-bank
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: krishna
    password: Todoroki@162
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/eazybank-dev/protocol/openid-connect/certs

server:
  port: 8089
